### 01 Create a Customer
POST http://localhost:5000/api/v1/customers
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByYXZlZW44QGV4YW1wbGUuY29tIiwiaWF0IjoxNzIxNzU0NTM4LCJleHAiOjE3MjE3NTgxMzh9.tfZslSXD9OzFSQ39aHWVFZcp-wCpXdQc4me41usy_XM

{
    "legal_company_name": "Company E",
    "default_currency": "USD",
    "address": "123 Street",
    "unit_floor": "1",
    "city": "City A",
    "state": "State A",
    "postal_code": "12345",
    "country": "Country A"
}


### 02 Show All Customers
GET http://localhost:5000/api/v1/customers
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByYXZlZW44QGV4YW1wbGUuY29tIiwiaWF0IjoxNzIxNzU0NTM4LCJleHAiOjE3MjE3NTgxMzh9.tfZslSXD9OzFSQ39aHWVFZcp-wCpXdQc4me41usy_XM
