### 01 Create a Product
POST http://localhost:5000/api/v1/products
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByYXZlZW44QGV4YW1wbGUuY29tIiwiaWF0IjoxNzIxMzcwNDMxLCJleHAiOjE3MjEzNzQwMzF9.83g9K0xpYTUayBqqdICfkhSqNtHa78zFnh8Fwe8GPxg

{
    "name": "Product 6",
    "internal_name": "Internal Product 1",
    "description": "Description for product 1",
    "charge_method": "recurring",
    "currency": "USD",
    "unit_price": 200,
    "status": "active",
    "last_activity": "2024-07-10T00:00:00Z"
}

### 02 Show All Products
GET http://localhost:5000/api/v1/products
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByYXZlZW44QGV4YW1wbGUuY29tIiwiaWF0IjoxNzIxMzcwNDMxLCJleHAiOjE3MjEzNzQwMzF9.83g9K0xpYTUayBqqdICfkhSqNtHa78zFnh8Fwe8GPxg


### 03 Change Product Status
PUT http://localhost:5000/api/v1/products/85a12e52-dd57-4270-9e8b-e1f815a4560c
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByYXZlZW44QGV4YW1wbGUuY29tIiwiaWF0IjoxNzIxMzcwNDMxLCJleHAiOjE3MjEzNzQwMzF9.83g9K0xpYTUayBqqdICfkhSqNtHa78zFnh8Fwe8GPxg


{
    "status": "inactive"
}
