
### 01 Create a Product
POST http://localhost:5000/api/v1/products
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByYXZlZW4xMUBleGFtcGxlLmNvbSIsImlhdCI6MTcyMTg5MDE1MCwiZXhwIjoxNzIxOTc2NTUwfQ.-rXvKTb1AYh7y4Kykpepq7JDFlw_SArUtVEMqmsunk0

{
    "name": "Product 15",
    "internal_name": "Internal Product 1",
    "description": "Description for product 1",
    "charge_method": "recurring",
    "currency": "USD",
    "unit_price": 200,
    "status": "active"
}


### 02 Show All Products
GET http://localhost:5000/api/v1/products
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByYXZlZW4xMUBleGFtcGxlLmNvbSIsImlhdCI6MTcyMTg5MDE1MCwiZXhwIjoxNzIxOTc2NTUwfQ.-rXvKTb1AYh7y4Kykpepq7JDFlw_SArUtVEMqmsunk0


### 03 Change Product Status
PUT http://localhost:5000/api/v1/products/086d5f76-85fd-4bc1-b584-93764f519cdc
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByYXZlZW4xMUBleGFtcGxlLmNvbSIsImlhdCI6MTcyMTg5MDE1MCwiZXhwIjoxNzIxOTc2NTUwfQ.-rXvKTb1AYh7y4Kykpepq7JDFlw_SArUtVEMqmsunk0


{
    "status": "active"
}
