
### 01 Create a Product
POST http://localhost:5000/api/v1/products
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByYXZlZW44QGV4YW1wbGUuY29tIiwiaWF0IjoxNzIxNzU0NTM4LCJleHAiOjE3MjE3NTgxMzh9.tfZslSXD9OzFSQ39aHWVFZcp-wCpXdQc4me41usy_XM

{
    "name": "Product 15",
    "internal_name": "Internal Product 1",
    "description": "Description for product 1",
    "charge_method": "recurring",
    "currency": "USD",
    "unit_price": 200,
    "status": "active",
    "last_activity": "2024-07-10T00:00:00Z"
}


### 02 Show All Products
GET http://localhost:5000/api/v1/products
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByYXZlZW44QGV4YW1wbGUuY29tIiwiaWF0IjoxNzIxNzU0NTM4LCJleHAiOjE3MjE3NTgxMzh9.tfZslSXD9OzFSQ39aHWVFZcp-wCpXdQc4me41usy_XM


### 03 Change Product Status
PUT http://localhost:5000/api/v1/products/528695e7-29f8-431c-a13a-f85cebe0b379
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByYXZlZW44QGV4YW1wbGUuY29tIiwiaWF0IjoxNzIxNzU0NTM4LCJleHAiOjE3MjE3NTgxMzh9.tfZslSXD9OzFSQ39aHWVFZcp-wCpXdQc4me41usy_XM


{
    "status": "active"
}
